# Site settings
title: "Jeremy Cote"
description: >
  Essays on physics, mathematics, and the quest for good explanations.

author: Jeremy Cote
email:
twitter_username:
github_username:

baseurl: "/paper-jekyll-theme" # the subpath of your site, e.g. /blog
url: "https://c-jeremy.github.io" # the base hostname & protocol for your site

google_analytics_id:
disqus_id:

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:year/:month/:title.html

sass:
    style: compressed

exclude: [vendor]
